# Generated by Django 6.0.1 on 2026-01-21 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_votes', models.IntegerField(default=0)),
                ('turnout_percentage', models.FloatField(default=0.0)),
                ('votes_per_hour_avg', models.FloatField(default=0.0)),
                ('peak_voting_hour', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AlterModelOptions(
            name='otp',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='constituency',
            name='registered_voters',
            field=models.IntegerField(default=0, help_text='Total registered voters'),
        ),
        migrations.AddField(
            model_name='vote',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='vote_day',
            field=models.CharField(blank=True, help_text='Day of week', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='vote_hour',
            field=models.IntegerField(blank=True, help_text='Hour of day (0-23)', null=True),
        ),
        migrations.AddField(
            model_name='voterprofile',
            name='age_group',
            field=models.CharField(blank=True, choices=[('18-25', '18-25'), ('26-35', '26-35'), ('36-50', '36-50'), ('51-65', '51-65'), ('65+', '65+')], help_text='Age group for demographic analysis', max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['timestamp'], name='voting_vote_timesta_1e3967_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['vote_hour'], name='voting_vote_vote_ho_98224a_idx'),
        ),
        migrations.AddField(
            model_name='votinganalytics',
            name='constituency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.constituency'),
        ),
        migrations.AlterUniqueTogether(
            name='votinganalytics',
            unique_together={('constituency', 'date')},
        ),
    ]
