# Generated by Django 6.0.1 on 2026-01-11 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('total_seats', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='voterprofile',
            name='voter_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='constituency',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='voting.constituency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voterprofile',
            name='constituency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='voting.constituency'),
        ),
    ]
